spring:
  application:
    name: msvc-course

  datasource:
    url: jdbc:postgresql://postgres_server_db:5432/msvc_course_db
    username: postgres
    password: toor
    driver-class-name: org.postgresql.Driver

  jpa:
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082

logging:
  file:
    path: /app/logs
  level:
    org.hibernate.sql: debug
